### ISSUE TITLE
Milestone 2 Presentation

### ISSUE THREAD

**Issue by AnushangaPavith** [cepdnaclk/e18-3yp-Smart-Planting-System#4]
Things to consider:
- [x] a brief and clear introduction to the project.
- [x] full details of the finalized solution architecture.
- [x] experience gained on relevant components and technologies (hardware, network communication, software).
- [x] progress on implementation work (demonstrations/photos/videos).
- [x] a plan for software/hardware testing (What? Why? How?).
- [x] Accurate budget/bill of materials.

Presentation
- [x] Make a presentation.
- [x] Practice.
